version: "3.8"

services:
  alpha-web:
    container_name: ${APP_NAME}-web
    build:
      context: "."
      dockerfile: Dockerfile
    image: ${APP_NAME}-image
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ${APP_NAME}-volume:/var/storage
    networks:
      - ${APP_NAME}-network
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 6G

volumes:
  alpha-volume:
    name: ${APP_NAME}-volume
